language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer self-update
  - composer install --dev --prefer-source
  - php vendor/autoload.php

script:
  - phpunit --configuration Tests/phpunit.xml --coverage-text

notifications:
  email: false
