language: php

php:
  - 7.3
  - 7.4
  - nightly

install:
  - composer install --no-interaction --dev --prefer-source

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit.xml.dist --colors --verbose

notifications:
  email: false
