language: php
php:
  - 5.5
  - 5.4
  - 5.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq curl
before_script:
  - time nslookup user-agent-string.info
  - ping -c 3 user-agent-string.info
  - time curl -fsq -o /dev/null "http://user-agent-string.info/rpc/get_data.php?key=free&format=ini&ver=y" || echo 'Could not contact user-agent-string.info'
  - time curl -i "http://user-agent-string.info/rpc/get_data.php?key=free&format=ini&ver=y"
script: phpunit Tests
